FROM node:13.12.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package*.json ./
RUN npm install

# add app
COPY . .

# add proxy
RUN npm install --save-dev http-proxy-middleware \
    && echo "const proxy = require('http-proxy-middleware'); module.exports = function(app) { app.use(proxy('/api', { target: 'http://host.docker.internal:5001/' })) }" > /app/src/setupProxy.js

# start app
CMD [ "npm", "start", "dev" ]

# docker build -t leaf_ui_client -f Dockerfile.dev .